name: Update wiki
on:
  pull_request:
    types: [opened, edited]
    branches:
      - main
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: openkfw/TruBudget.wiki
      - name: Validate the files
        run: |
          git config user.email "trubudget.devteam@accenture.com"
          git config user.name "System bot"
          echo "some data for the file" >> Security-vulnerability-report.md
          git add .
          git commit -m "Test change"
          git push
        shell: bash